package events

import "time"

// Event represents a lifecycle event generated by URX.
type Event struct {
	ID        string    `json:"id"`
	Timestamp time.Time `json:"timestamp"`
	Type      string    `json:"type"`
	Component string    `json:"component"`
	RunID     string    `json:"run_id,omitempty"`
	Message   string    `json:"message,omitempty"`
}

// Event types emitted by URX.
const (
	RunStarted   = "run.started"
	RunCompleted = "run.completed"
	RunFailed    = "run.failed"

	DeployStarted   = "deploy.started"
	DeployCompleted = "deploy.completed"
	DeployFailed    = "deploy.failed"

	ContainerStarted = "container.started"
	ContainerFailed  = "container.failed"
)
